server:
  port: 9095

app:
  messaging.kafka.broker: 127.0.0.1

spring:
  application.name: producer
  cloud:
    stream:
      defaultBinder: kafka
      kafka.binder:
        brokers: ${app.messaging.kafka.broker}
        defaultBrokerPort: 9092
      default.contentType: application/json
      bindings:
        messageProducer-out-0:
          destination: messages
          producer.requiredGroups: messageGroup

---
spring:
  profiles: docker

server.port: 8080

app:
  messaging.kafka.broker: kafka

---
spring:
  profiles: kafka
  cloud.stream.defaultBinder: kafka
  kafka.bootstrap-servers: kafka:9092
